In [1]:
print("s")

s

In [4]:
import pandas as pd

In [5]:
data1 = {"name":["Ali","Hamza","Syed","Akbar"],
        "age":[12,25,11,17],
        "GPA":[3,4,2,1]
       }

In [6]:
df = pd.DataFrame(data1)

In [7]:
print(df)

    name  age  GPA
0    Ali   12    3
1  Hamza   25    4
2   Syed   11    2
3  Akbar   17    1

In [8]:
print(df[df["GPA"] > 1])

    name  age  GPA
0    Ali   12    3
1  Hamza   25    4
2   Syed   11    2

In [9]:
df.head()

    name  age  GPA
0    Ali   12    3
1  Hamza   25    4
2   Syed   11    2
3  Akbar   17    1

In [10]:
print("average : ",df["GPA"].mean())

average :  2.5

In [11]:
Customers = pd.read_csv("Customers.csv")

In [12]:
OrderItems = pd.read_csv("Order_Items.csv")

In [13]:
geolocation= pd.read_csv("geolocation.csv")

In [14]:
Order_payments = pd.read_csv("order_payments.csv")

In [15]:
order_reviews = pd.read_csv("Order_reviews.csv")

In [16]:
Orders = pd.read_csv("Orders.csv")

In [28]:
products = pd.read_csv("products.csv")

In [18]:
sellers = pd.read_csv("sellers.csv")

In [19]:
product_category = pd.read_csv("product_category_name_translation.csv")

In [20]:
Orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [21]:
Customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [22]:
result = pd.merge(Customers,Orders, on="customer_id", how ="inner")

In [23]:
OrderItems.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [24]:
result = OrderItems.groupby('seller_id').agg({
    'price': ['mean', 'sum'],
    'freight_value': 'max'
})

result.head()

                                       price           freight_value
                                        mean       sum           max
seller_id
0015a82c2db000af6aaaf3ae2ecb0532  895.000000   2685.00         21.02
001cca7ae9ae17fb1caed9dfb1094831  104.937364  25080.03        114.62
001e6ad469a905060d959994f1b41e4f  250.000000    250.00         17.94
002100f778ceb8431b7a1020ff7ab48f   22.445455   1234.50         34.15
003554e2dce176b5555353e4f3555ac8  120.000000    120.00         19.38

In [27]:
result.columns = ['avg_price','total_price','max_freight']
result.head()

                                   avg_price  total_price  max_freight
seller_id
0015a82c2db000af6aaaf3ae2ecb0532  895.000000      2685.00        21.02
001cca7ae9ae17fb1caed9dfb1094831  104.937364     25080.03       114.62
001e6ad469a905060d959994f1b41e4f  250.000000       250.00        17.94
002100f778ceb8431b7a1020ff7ab48f   22.445455      1234.50        34.15
003554e2dce176b5555353e4f3555ac8  120.000000       120.00        19.38

In [31]:
print("Customers:", Customers.shape)
print("Orders:", Orders.shape)

Customers: (99441, 5)
Orders: (99441, 8)

In [32]:
inner = pd.merge(
    Customers,
    Orders,
    on='customer_id',
    how='inner'
)

print(inner.shape)

(99441, 12)

In [33]:
left = pd.merge(
    Customers,
    Orders,
    on='customer_id',
    how='left'
)

print(left.shape)

(99441, 12)

In [34]:
outer = pd.merge(
    Customers,
    Orders,
    on='customer_id',
    how='outer'
)

print(outer.shape)

(99441, 12)

In [35]:
print("Customers:", Customers.shape)
print("Orders:", Orders.shape)

print("Inner:", inner.shape)
print("Left:", left.shape)
print("Outer:", outer.shape)

Customers: (99441, 5)
Orders: (99441, 8)
Inner: (99441, 12)
Left: (99441, 12)
Outer: (99441, 12)

In [36]:
def price_category(price):   # .apply
    if price > 100:
        return 'Expensive'
    else:
        return 'Cheap'

In [37]:
OrderItems['price_category'] = OrderItems['price'].apply(price_category)

In [38]:
OrderItems[['price', 'price_category']].head()

    price price_category
0   58.90          Cheap
1  239.90      Expensive
2  199.00      Expensive
3   12.99          Cheap
4  199.90      Expensive

In [41]:
#vectorize
import numpy as np
OrderItems['price_category'] = np.where(
    OrderItems['price'] > 100,
    'Expensive',
    'Cheap'
)

In [53]:
print(" .apply : ")
%timeit OrderItems['price'].apply(lambda x: 'Expensive' if x > 100 else 'Cheap')

 .apply :
15.8 ms ± 449 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [51]:
print("vectorized : ")
%timeit np.where(OrderItems['price'] > 100,'Expensive','Cheap')

vectorized :
1.66 ms ± 20.5 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [54]:
tables = {
    'Customers': Customers,
    'Geolocation': geolocation,
    'Order Items': OrderItems,
    'Order Payments': Order_payments,
    'Order Reviews': order_reviews,
    'Orders': Orders,
    'Products': products,
    'Sellers': sellers,
    'Product Category Translation': product_category
}

for name, df in tables.items():
    print(f"{name}: {df.shape}")

Customers: (99441, 5)
Geolocation: (1000163, 5)
Order Items: (112650, 8)
Order Payments: (103886, 5)
Order Reviews: (99224, 7)
Orders: (99441, 8)
Products: (32951, 9)
Sellers: (3095, 4)
Product Category Translation: (71, 2)

In [55]:
for name, df in tables.items():
    print("\n" + "="*50)
    print(name)
    print(df.columns.tolist())

==================================================
Customers
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

==================================================
Geolocation
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

==================================================
Order Items
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value', 'price_category']

==================================================
Order Payments
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

==================================================
Order Reviews
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

==================================================
Orders
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

==================================================
Products
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

==================================================
Sellers
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

==================================================
Product Category Translation
['product_category_name', 'product_category_name_english']

In [56]:
orphan_order_items = OrderItems[
    ~OrderItems['order_id'].isin(Orders['order_id'])
]

print("Orphan OrderItems:", len(orphan_order_items))

Orphan OrderItems: 0

In [57]:
orphan_payments = Order_payments[
    ~Order_payments['order_id'].isin(Orders['order_id'])
]

print("Orphan Payments:", len(orphan_payments))

Orphan Payments: 0

In [58]:
orphan_reviews = order_reviews[
    ~order_reviews['order_id'].isin(Orders['order_id'])
]

print("Orphan Reviews:", len(orphan_reviews))

Orphan Reviews: 0

In [59]:
orphan_customers = Orders[
    ~Orders['customer_id'].isin(Customers['customer_id'])
]

print("Orphan customer IDs:", len(orphan_customers))

Orphan customer IDs: 0

In [60]:
orphan_products = OrderItems[
    ~OrderItems['product_id'].isin(products['product_id'])
]

print("Orphan product IDs:", len(orphan_products))

Orphan product IDs: 0

In [61]:
orphan_sellers = OrderItems[
    ~OrderItems['seller_id'].isin(sellers['seller_id'])
]

print("Orphan seller IDs:", len(orphan_sellers))

Orphan seller IDs: 0

In [62]:
checks = {
    'OrderItems → Orders': (
        ~OrderItems['order_id'].isin(Orders['order_id'])
    ).sum(),

    'Payments → Orders': (
        ~Order_payments['order_id'].isin(Orders['order_id'])
    ).sum(),

    'Reviews → Orders': (
        ~order_reviews['order_id'].isin(Orders['order_id'])
    ).sum(),

    'Orders → Customers': (
        ~Orders['customer_id'].isin(Customers['customer_id'])
    ).sum(),

    'OrderItems → Products': (
        ~OrderItems['product_id'].isin(products['product_id'])
    ).sum(),

    'OrderItems → Sellers': (
        ~OrderItems['seller_id'].isin(sellers['seller_id'])
    ).sum()
}

for relationship, count in checks.items():
    print(f"{relationship}: {count} orphan keys")

OrderItems → Orders: 0 orphan keys
Payments → Orders: 0 orphan keys
Reviews → Orders: 0 orphan keys
Orders → Customers: 0 orphan keys
OrderItems → Products: 0 orphan keys
OrderItems → Sellers: 0 orphan keys