In [1]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:pass@localhost:5432/postgres"
)

print("Connection successful!")

Connection successful!

In [2]:
import pandas as pd

test_df = pd.DataFrame({
    "name": ["Shoaib", "Ali", "Ahmed"],
    "age": [24, 25, 23]
})

test_df.to_sql(
    "test_table",
    engine,
    if_exists="replace",
    index=False
)

print("Table uploaded successfully!")

Table uploaded successfully!

In [19]:

product_category_df = pd.read_csv("cleaned_product_category.csv")
sellers_df = pd.read_csv("cleaned_sellers.csv")
products_df = pd.read_csv("cleaned_products.csv")
orders_df = pd.read_csv("cleaned_Orders.csv")
order_reviews_df = pd.read_csv("cleaned_order_reviews.csv")
order_payments_df = pd.read_csv("cleaned_order_payments.csv")
geolocation_df= pd.read_csv("cleaned_geolocation.csv")
order_items_df = pd.read_csv("cleaned_OrderItems.csv")
customers_df = pd.read_csv("cleaned_Customers.csv")

In [23]:
product_category_df.to_sql(
    "product_category", engine, if_exists="replace", index=False
)

sellers_df.to_sql(
    "sellers", engine, if_exists="replace", index=False
)

products_df.to_sql(
    "products", engine, if_exists="replace", index=False
)

orders_df.to_sql(
    "orders", engine, if_exists="replace", index=False
)

order_reviews_df.to_sql(
    "order_reviews", engine, if_exists="replace", index=False
)

order_payments_df.to_sql(
    "order_payments", engine, if_exists="replace", index=False
)

geolocation_df.to_sql(
    "geolocation", engine, if_exists="replace", index=False
)

order_items_df.to_sql(
    "order_items", engine, if_exists="replace", index=False
)

customers_df.to_sql(
    "customers", engine, if_exists="replace", index=False
)

print("All 9 tables uploaded successfully!")

All 9 tables uploaded successfully!

In [24]:
from sqlalchemy import text

with engine.connect() as connection:
    result = connection.execute(text("""
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = 'public'
        ORDER BY table_name;
    """))

    for row in result:
        print(row[0])

customers
geolocation
order_items
order_payments
order_reviews
orders
product_category
products
sellers
test_table

In [25]:
from sqlalchemy import text

tables = [
    "product_category",
    "sellers",
    "products",
    "orders",
    "order_reviews",
    "order_payments",
    "geolocation",
    "order_items",
    "customers"
]

for table in tables:
    print(f"\n--- {table} ---")

    with engine.connect() as conn:
        result = conn.execute(text(f"""
            SELECT column_name, data_type
            FROM information_schema.columns
            WHERE table_name = '{table}'
            ORDER BY ordinal_position;
        """))

        for row in result:
            print(row)

--- product_category ---
('product_category_name', 'text')
('product_category_name_english', 'text')

--- sellers ---
('seller_id', 'text')
('seller_zip_code_prefix', 'bigint')
('seller_city', 'text')
('seller_state', 'text')

--- products ---
('product_id', 'text')
('product_category_name', 'text')
('product_name_lenght', 'double precision')
('product_description_lenght', 'double precision')
('product_photos_qty', 'double precision')
('product_weight_g', 'double precision')
('product_length_cm', 'double precision')
('product_height_cm', 'double precision')
('product_width_cm', 'double precision')

--- orders ---
('order_id', 'text')
('customer_id', 'text')
('order_status', 'text')
('order_purchase_timestamp', 'text')
('order_approved_at', 'text')
('order_delivered_carrier_date', 'text')
('order_delivered_customer_date', 'text')
('order_estimated_delivery_date', 'text')

--- order_reviews ---
('review_id', 'text')
('order_id', 'text')
('review_score', 'bigint')
('review_comment_title', 'text')
('review_comment_message', 'text')
('review_creation_date', 'text')
('review_answer_timestamp', 'text')

--- order_payments ---
('order_id', 'text')
('payment_sequential', 'bigint')
('payment_type', 'text')
('payment_installments', 'bigint')
('payment_value', 'double precision')

--- geolocation ---
('geolocation_zip_code_prefix', 'bigint')
('geolocation_lat', 'double precision')
('geolocation_lng', 'double precision')
('geolocation_city', 'text')
('geolocation_state', 'text')

--- order_items ---
('order_id', 'text')
('order_item_id', 'bigint')
('product_id', 'text')
('seller_id', 'text')
('shipping_limit_date', 'text')
('price', 'double precision')
('freight_value', 'double precision')

--- customers ---
('customer_id', 'text')
('customer_unique_id', 'text')
('customer_zip_code_prefix', 'bigint')
('customer_city', 'text')
('customer_state', 'text')

In [26]:
query = """
SELECT
    pc.product_category_name,
    SUM(oi.price) AS total_revenue
FROM order_items oi

INNER JOIN products p
    ON oi.product_id = p.product_id

INNER JOIN product_category pc
    ON p.product_category_name = pc.product_category_name

GROUP BY pc.product_category_name
ORDER BY total_revenue DESC
LIMIT 10;
"""

top_categories = pd.read_sql(query, engine)

top_categories

    product_category_name  total_revenue
0            beleza_saude     1258681.34
1      relogios_presentes     1205005.68
2         cama_mesa_banho     1036988.68
3           esporte_lazer      988048.97
4  informatica_acessorios      911954.32
5        moveis_decoracao      729762.49
6              cool_stuff      635290.85
7   utilidades_domesticas      632248.66
8              automotivo      592720.11
9      ferramentas_jardim      485256.46

In [27]:
query = """
SELECT
    COUNT(*) FILTER (WHERE order_count > 1) AS repeat_customers,
    COUNT(*) AS total_customers,
    ROUND(
        100.0 * COUNT(*) FILTER (WHERE order_count > 1) / COUNT(*),
        2
    ) AS repeat_customer_rate
FROM (
    SELECT
        customer_id,
        COUNT(order_id) AS order_count
    FROM orders
    GROUP BY customer_id
) customer_orders;
"""

repeat_rate = pd.read_sql(query, engine)

repeat_rate

   repeat_customers  total_customers  repeat_customer_rate
0                 0            99441                   0.0

In [29]:
customers_df.columns.tolist()

['customer_id',
 'customer_unique_id',
 'customer_zip_code_prefix',
 'customer_city',
 'customer_state']

In [30]:
query = """
-- Business Question: What percentage of customers placed more than one order?
-- INNER JOIN is used because we only need orders that have a matching customer.
-- customer_unique_id identifies the actual customer across multiple orders.

SELECT
    COUNT(*) FILTER (WHERE order_count > 1) AS repeat_customers,
    COUNT(*) AS total_customers,
    ROUND(
        100.0 * COUNT(*) FILTER (WHERE order_count > 1) / COUNT(*),
        2
    ) AS repeat_customer_rate
FROM (
    SELECT
        c.customer_unique_id,
        COUNT(o.order_id) AS order_count
    FROM orders o
    INNER JOIN customers c
        ON o.customer_id = c.customer_id
    GROUP BY c.customer_unique_id
) customer_orders;
"""

repeat_rate = pd.read_sql(query, engine)

repeat_rate

   repeat_customers  total_customers  repeat_customer_rate
0              2997            96096                  3.12

In [33]:
query = """
-- Business Question: What is the average delivery time by customer state?
-- INNER JOIN is used because we only want orders with a matching customer.
-- The date columns are cast to TIMESTAMP because they were stored as TEXT.

SELECT
    c.customer_state,
    ROUND(
        AVG(
            EXTRACT(
                EPOCH FROM (
                    o.order_delivered_customer_date::timestamp
                    - o.order_purchase_timestamp::timestamp
                )
            ) / 86400
        ),
        2
    ) AS avg_delivery_days
FROM orders o

INNER JOIN customers c
    ON o.customer_id = c.customer_id

WHERE o.order_delivered_customer_date IS NOT NULL

GROUP BY c.customer_state

ORDER BY avg_delivery_days;
"""

delivery_by_state = pd.read_sql(query, engine)

delivery_by_state

   customer_state  avg_delivery_days
0              SP               8.76
1              PR              11.99
2              MG              12.01
3              DF              12.97
4              SC              14.96
5              RS              15.30
6              RJ              15.31
7              GO              15.61
8              MS              15.62
9              ES              15.79
10             TO              17.66
11             MT              18.06
12             PE              18.45
13             RN              19.28
14             BA              19.34
15             RO              19.37
16             PI              19.46
17             PB              20.43
18             AC              21.04
19             CE              21.27
20             SE              21.52
21             MA              21.57
22             PA              23.77
23             AL              24.54
24             AM              26.43
25             AP              27.19
26             RR              29.39

In [36]:
query = """
-- Business Question: What are the top 10 product categories by total revenue?
-- INNER JOIN is used because we only want products with matching
-- order and category information.

SELECT
    pc.product_category_name,
    ROUND(SUM(oi.price)::numeric, 2) AS total_revenue
FROM order_items oi

INNER JOIN products p
    ON oi.product_id = p.product_id

INNER JOIN product_category pc
    ON p.product_category_name = pc.product_category_name

GROUP BY pc.product_category_name

ORDER BY total_revenue DESC

LIMIT 10;
"""

top_categories = pd.read_sql(query, engine)

top_categories

    product_category_name  total_revenue
0            beleza_saude     1258681.34
1      relogios_presentes     1205005.68
2         cama_mesa_banho     1036988.68
3           esporte_lazer      988048.97
4  informatica_acessorios      911954.32
5        moveis_decoracao      729762.49
6              cool_stuff      635290.85
7   utilidades_domesticas      632248.66
8              automotivo      592720.11
9      ferramentas_jardim      485256.46

In [37]:
query = """
-- Business Question: Which product categories and seller states
-- generate the most revenue?
--
-- INNER JOIN is used because we only want records that have
-- matching information in all related tables.

SELECT
    pc.product_category_name,
    s.seller_state,
    COUNT(DISTINCT oi.order_id) AS total_orders,
    ROUND(SUM(oi.price)::numeric, 2) AS total_revenue,
    ROUND(AVG(oi.price)::numeric, 2) AS average_item_price

FROM order_items oi

INNER JOIN products p
    ON oi.product_id = p.product_id

INNER JOIN product_category pc
    ON p.product_category_name = pc.product_category_name

INNER JOIN sellers s
    ON oi.seller_id = s.seller_id

GROUP BY
    pc.product_category_name,
    s.seller_state

ORDER BY total_revenue DESC;
"""

category_seller_revenue = pd.read_sql(query, engine)

category_seller_revenue.head(20)

,product_category_name,seller_state,total_orders,total_revenue,average_item_price
0,relogios_presentes,sp,4588,971086.60,201.05
1,cama_mesa_banho,sp,8336,909463.04,92.63
2,beleza_saude,sp,5820,697858.50,108.97
3,esporte_lazer,sp,4902,610096.61,111.66
4,moveis_decoracao,sp,4688,498629.41,79.70
5,cool_stuff,sp,2668,445749.45,160.28
6,utilidades_domesticas,sp,4120,390579.26,78.87
7,automotivo,sp,3086,388360.37,116.21
8,informatica_acessorios,sp,2879,353728.74,106.32
9,bebes,sp,2040,301349.43,139.26
10,brinquedos,sp,2685,278086.55,97.27
11,ferramentas_jardim,sp,2402,262609.13,85.46
12,moveis_escritorio,sp,1217,251237.91,154.99
13,perfumaria,sp,2101,227363.61,99.42
14,informatica_acessorios,pr,1296,201758.43,124.01
15,telefonia,sp,3639,194378.26,49.67
16,beleza_saude,rj,978,183336.32,171.18
17,esporte_lazer,pr,1204,175925.86,132.37
18,papelaria,sp,1776,173967.74,89.17
19,informatica_acessorios,mg,1394,172808.63,109.72

In [38]:
query = """
-- LEFT JOIN keeps every product even if it has never been ordered.
-- Use LEFT JOIN when we want to keep all records from the left table.

SELECT
    p.product_id,
    pc.product_category_name,
    COUNT(oi.order_id) AS times_ordered

FROM products p

LEFT JOIN order_items oi
    ON p.product_id = oi.product_id

LEFT JOIN product_category pc
    ON p.product_category_name = pc.product_category_name

GROUP BY
    p.product_id,
    pc.product_category_name

ORDER BY times_ordered ASC;
"""

product_orders = pd.read_sql(query, engine)

product_orders.head(20)

,product_id,product_category_name,times_ordered
0,fe1d68f123061329a6d3505c2b905566,moveis_decoracao,1
1,8cea3a70558be2f35507686686c183af,esporte_lazer,1
2,ba22b6bb8962ab07830d463eeff99b9d,cama_mesa_banho,1
3,f3637eb5ce07d19f2f9eca6bb7dc29d6,automotivo,1
4,ba1d7e7ee1f055d252a2faa8ea3cea9b,agro_industria_e_comercio,1
5,ba1cc0f3f26616d7ad90de1085bdfeda,malas_acessorios,1
6,ba1b78ee2d24870c2bb5c4be33af89eb,relogios_presentes,1
7,ba1adcf388392101517056482eb5c849,brinquedos,1
8,8cf22b2cc9465d64474a09853b62f5b2,utilidades_domesticas,1
9,17f05cc6ef5563b5e096ab059ca926b4,cama_mesa_banho,1
10,8cf7e354e6d9f04a09f4d59bc77dcc8e,construcao_ferramentas_jardim,1
11,8cf897d3f22f0f721c4c5ba6d5708684,climatizacao,1
12,8cf9973ba86ba4067dc5de39d247c47d,automotivo,1
13,17f1ae71c27aaad9cee4655e62a50189,informatica_acessorios,1
14,8cfcfc09db52830c8dab9e5a36d7ae6b,esporte_lazer,1
15,ba18c48184ce58f0ffd8b656c4edf21c,cama_mesa_banho,1
16,8d027132a8818b4d661e9d83778f8bd0,automotivo,1
17,8d05b2c8739a97a9b912b206eed6a0aa,papelaria,1
18,8d063218dab590d1a369a08e761c16e1,beleza_saude,1
19,ba17dd83b93da33a4483ba301644f40a,relogios_presentes,1

In [39]:
#task2

In [40]:
query = """
-- Rank sellers by total revenue within each state.
-- DENSE_RANK() gives sellers the same rank when they have
-- the same revenue, without skipping the next rank.

WITH seller_revenue AS (
    SELECT
        s.seller_id,
        s.seller_state,
        SUM(oi.price) AS total_revenue
    FROM order_items oi

    INNER JOIN sellers s
        ON oi.seller_id = s.seller_id

    GROUP BY
        s.seller_id,
        s.seller_state
)

SELECT
    seller_id,
    seller_state,
    ROUND(total_revenue::numeric, 2) AS total_revenue,

    DENSE_RANK() OVER (
        PARTITION BY seller_state
        ORDER BY total_revenue DESC
    ) AS revenue_rank

FROM seller_revenue

ORDER BY
    seller_state,
    revenue_rank;
"""

seller_ranking = pd.read_sql(query, engine)

seller_ranking.head(20)

                           seller_id seller_state  total_revenue  revenue_rank
0   4be2e7f96b4fd749d52dff41f80e39dd           ac         267.00             1
1   327b89b872c14d1c0be7235ef4871685           am        1177.00             1
2   53243585a1d6dc2643021fd1853d8905           ba      222776.05             1
3   c72de06d72748d1a0dfb2125be43ba63           ba       17522.00             2
4   75d34ebb1bd0bd7dde40dd507b8169c3           ba       15048.28             3
5   d03698c2efd04a549382afa6623e27fb           ba        8865.47             4
6   4aba391bc3b88717ce08eb11e44937b2           ba        7595.87             5
7   a3dd39f583bc80bd8c5901c95878921e           ba        4607.81             6
8   1444c08e64d55fb3c25f0f09c07ffcf2           ba        2749.00             7
9   659e8466eb3ff1b0e8740d74fb7bbedd           ba        1486.80             8
10  d2e753bb80b7d4faa77483ed00edc8ca           ba        1320.70             9
11  4fb41dff7c50136976d1a5cf004a42e2           ba        1230.00            10
12  4221a7df464f1fe2955934e30ff3a5a1           ba         849.50            11
13  fc59392d66ef99377e50356ee4f3b4e1           ba         519.99            12
14  2b402d5dc42554061f8ea98d1916f148           ba         299.89            13
15  651530bf5c607240ccdd89a30c9c9712           ba         199.90            14
16  b00af24704019bd2e1b335e70ad11f7c           ba         189.00            15
17  398cb257329ef7af7f1943a8974a3cbc           ba         145.90            16
18  f3055483058c84d75ca2a3314fb4deef           ba          67.50            17
19  eb4a59a06b3948e851a7d7a830bcbc42           ba          64.00            18

In [44]:
query = """
-- Calculate monthly order volume and compare it with
-- the previous month's order volume for each category.
--
-- LAG() gets the value from the previous month.

WITH monthly_orders AS (
    SELECT
        DATE_TRUNC(
            'month',
            o.order_purchase_timestamp::timestamp
        ) AS order_month,

        pc.product_category_name,

        COUNT(DISTINCT oi.order_id) AS order_volume

    FROM orders o

    INNER JOIN order_items oi
        ON o.order_id = oi.order_id

    INNER JOIN products p
        ON oi.product_id = p.product_id

    INNER JOIN product_category pc
        ON p.product_category_name = pc.product_category_name

    GROUP BY
        order_month,
        pc.product_category_name
)

SELECT
    order_month,
    product_category_name,
    order_volume,

    LAG(order_volume) OVER (
        PARTITION BY product_category_name
        ORDER BY order_month
    ) AS previous_month_orders,

    order_volume -
    LAG(order_volume) OVER (
        PARTITION BY product_category_name
        ORDER BY order_month
    ) AS month_over_month_change

FROM monthly_orders

ORDER BY
    product_category_name,
    order_month;
"""

monthly_category_orders = pd.read_sql(query, engine)

monthly_category_orders.head(20)

,order_month,product_category_name,order_volume,previous_month_orders,month_over_month_change
0,2017-01-01,agro_industria_e_comercio,2,NaN,NaN
1,2017-02-01,agro_industria_e_comercio,7,2.0,5.0
2,2017-03-01,agro_industria_e_comercio,2,7.0,-5.0
3,2017-05-01,agro_industria_e_comercio,4,2.0,2.0
4,2017-06-01,agro_industria_e_comercio,1,4.0,-3.0
5,2017-07-01,agro_industria_e_comercio,1,1.0,0.0
6,2017-08-01,agro_industria_e_comercio,1,1.0,0.0
7,2017-09-01,agro_industria_e_comercio,3,1.0,2.0
8,2017-10-01,agro_industria_e_comercio,5,3.0,2.0
9,2017-11-01,agro_industria_e_comercio,13,5.0,8.0
10,2017-12-01,agro_industria_e_comercio,9,13.0,-4.0
11,2018-01-01,agro_industria_e_comercio,15,9.0,6.0
12,2018-02-01,agro_industria_e_comercio,21,15.0,6.0
13,2018-03-01,agro_industria_e_comercio,25,21.0,4.0
14,2018-04-01,agro_industria_e_comercio,12,25.0,-13.0
15,2018-05-01,agro_industria_e_comercio,8,12.0,-4.0
16,2018-06-01,agro_industria_e_comercio,10,8.0,2.0
17,2018-07-01,agro_industria_e_comercio,29,10.0,19.0
18,2018-08-01,agro_industria_e_comercio,14,29.0,-15.0
19,2016-10-01,alimentos,1,NaN,NaN

In [45]:
query = """
-- Calculate monthly revenue and cumulative revenue over time.
-- SUM() OVER() creates a running total while keeping
-- each individual month's revenue.

WITH monthly_revenue AS (
    SELECT
        DATE_TRUNC(
            'month',
            o.order_purchase_timestamp::timestamp
        ) AS order_month,

        SUM(oi.price) AS monthly_revenue

    FROM orders o

    INNER JOIN order_items oi
        ON o.order_id = oi.order_id

    GROUP BY order_month
)

SELECT
    order_month,

    ROUND(monthly_revenue::numeric, 2) AS monthly_revenue,

    ROUND(
        SUM(monthly_revenue) OVER (
            ORDER BY order_month
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        )::numeric,
        2
    ) AS cumulative_revenue

FROM monthly_revenue

ORDER BY order_month;
"""

cumulative_revenue = pd.read_sql(query, engine)

cumulative_revenue.head(20)

   order_month  monthly_revenue  cumulative_revenue
0   2016-09-01           267.36              267.36
1   2016-10-01         49507.66            49775.02
2   2016-12-01            10.90            49785.92
3   2017-01-01        120312.87           170098.79
4   2017-02-01        247303.02           417401.81
5   2017-03-01        374344.30           791746.11
6   2017-04-01        359927.23          1151673.34
7   2017-05-01        506071.14          1657744.48
8   2017-06-01        433038.60          2090783.08
9   2017-07-01        498031.48          2588814.56
10  2017-08-01        573971.68          3162786.24
11  2017-09-01        624401.69          3787187.93
12  2017-10-01        664219.43          4451407.36
13  2017-11-01       1010271.37          5461678.73
14  2017-12-01        743914.17          6205592.90
15  2018-01-01        950030.36          7155623.26
16  2018-02-01        844178.71          7999801.97
17  2018-03-01        983213.44          8983015.41
18  2018-04-01        996647.75          9979663.16
19  2018-05-01        996517.68         10976180.84

In [46]:
#Revenue increased steadily over the period, reaching approximately 10.98 million by May 2018. 
#Monthly revenue generally grew over time, with November 2017 recording about 1.01 million, one of the
# highest monthly revenues in the displayed results.

In [47]:
#task 3

In [49]:
query = """
-- Calculate customer cohort retention by month.
-- This answers: What percentage of customers from each cohort
-- returned and made purchases in subsequent months?

WITH cohort AS (
    SELECT
        customer_id,
        DATE_TRUNC(
            'month',
            MIN(order_purchase_timestamp::timestamp)
        ) AS cohort_month
    FROM orders
    GROUP BY customer_id
),

orders_by_month AS (
    SELECT DISTINCT
        o.customer_id,
        DATE_TRUNC(
            'month',
            o.order_purchase_timestamp::timestamp
        ) AS order_month,
        c.cohort_month
    FROM orders o
    INNER JOIN cohort c
        ON o.customer_id = c.customer_id
),

cohort_activity AS (
    SELECT
        cohort_month,
        order_month,
        COUNT(DISTINCT customer_id) AS active_customers
    FROM orders_by_month
    GROUP BY
        cohort_month,
        order_month
)

SELECT
    cohort_month,
    order_month,
    active_customers,

    ROUND(
        100.0 * active_customers /
        MAX(
            CASE
                WHEN order_month = cohort_month
                THEN active_customers
            END
        ) OVER (
            PARTITION BY cohort_month
        ),
        2
    ) AS retention_percentage

FROM cohort_activity

WHERE order_month >= cohort_month

ORDER BY
    cohort_month,
    order_month;
"""

cohort_retention = pd.read_sql(query, engine)

cohort_retention.head(50)

   cohort_month order_month  active_customers  retention_percentage
0    2016-09-01  2016-09-01                 4                 100.0
1    2016-10-01  2016-10-01               324                 100.0
2    2016-12-01  2016-12-01                 1                 100.0
3    2017-01-01  2017-01-01               800                 100.0
4    2017-02-01  2017-02-01              1780                 100.0
5    2017-03-01  2017-03-01              2682                 100.0
6    2017-04-01  2017-04-01              2404                 100.0
7    2017-05-01  2017-05-01              3700                 100.0
8    2017-06-01  2017-06-01              3245                 100.0
9    2017-07-01  2017-07-01              4026                 100.0
10   2017-08-01  2017-08-01              4331                 100.0
11   2017-09-01  2017-09-01              4285                 100.0
12   2017-10-01  2017-10-01              4631                 100.0
13   2017-11-01  2017-11-01              7544                 100.0
14   2017-12-01  2017-12-01              5673                 100.0
15   2018-01-01  2018-01-01              7269                 100.0
16   2018-02-01  2018-02-01              6728                 100.0
17   2018-03-01  2018-03-01              7211                 100.0
18   2018-04-01  2018-04-01              6939                 100.0
19   2018-05-01  2018-05-01              6873                 100.0
20   2018-06-01  2018-06-01              6167                 100.0
21   2018-07-01  2018-07-01              6292                 100.0
22   2018-08-01  2018-08-01              6512                 100.0
23   2018-09-01  2018-09-01                16                 100.0
24   2018-10-01  2018-10-01                 4                 100.0

In [56]:
query = """
-- Calculate customer cohort retention by month.
-- This answers: What percentage of customers from each cohort
-- returned and made a purchase in subsequent months?

WITH cohort AS (
    SELECT
        c.customer_unique_id,
        DATE_TRUNC(
            'month',
            MIN(o.order_purchase_timestamp::timestamp)
        ) AS cohort_month
    FROM orders o
    INNER JOIN customers c
        ON o.customer_id = c.customer_id
    GROUP BY c.customer_unique_id
),

orders_by_month AS (
    SELECT DISTINCT
        c.customer_unique_id,
        DATE_TRUNC(
            'month',
            o.order_purchase_timestamp::timestamp
        ) AS order_month,
        co.cohort_month
    FROM orders o
    INNER JOIN customers c
        ON o.customer_id = c.customer_id
    INNER JOIN cohort co
        ON c.customer_unique_id = co.customer_unique_id
),

cohort_activity AS (
    SELECT
        cohort_month,
        order_month,
        COUNT(DISTINCT customer_unique_id) AS active_customers
    FROM orders_by_month
    GROUP BY
        cohort_month,
        order_month
)

SELECT
    cohort_month,
    order_month,
    active_customers,

    ROUND(
        100.0 * active_customers /
        MAX(
            CASE
                WHEN order_month = cohort_month
                THEN active_customers
            END
        ) OVER (
            PARTITION BY cohort_month
        ),
        2
    ) AS retention_percentage

FROM cohort_activity

WHERE order_month >= cohort_month

ORDER BY
    cohort_month,
    order_month;
"""

cohort_retention = pd.read_sql(query, engine)

cohort_retention.head(50)

   cohort_month order_month  active_customers  retention_percentage
0    2016-09-01  2016-09-01                 4                100.00
1    2016-10-01  2016-10-01               321                100.00
2    2016-10-01  2017-04-01                 1                  0.31
3    2016-10-01  2017-07-01                 1                  0.31
4    2016-10-01  2017-09-01                 1                  0.31
5    2016-10-01  2017-11-01                 1                  0.31
6    2016-10-01  2018-01-01                 1                  0.31
7    2016-10-01  2018-03-01                 1                  0.31
8    2016-10-01  2018-05-01                 2                  0.62
9    2016-10-01  2018-06-01                 2                  0.62
10   2016-12-01  2016-12-01                 1                100.00
11   2016-12-01  2017-01-01                 1                100.00
12   2017-01-01  2017-01-01               764                100.00
13   2017-01-01  2017-02-01                 3                  0.39
14   2017-01-01  2017-03-01                 2                  0.26
15   2017-01-01  2017-04-01                 1                  0.13
16   2017-01-01  2017-05-01                 3                  0.39
17   2017-01-01  2017-06-01                 1                  0.13
18   2017-01-01  2017-07-01                 4                  0.52
19   2017-01-01  2017-08-01                 1                  0.13
20   2017-01-01  2017-09-01                 1                  0.13
21   2017-01-01  2017-11-01                 3                  0.39
22   2017-01-01  2017-12-01                 1                  0.13
23   2017-01-01  2018-01-01                 6                  0.79
24   2017-01-01  2018-02-01                 3                  0.39
25   2017-01-01  2018-03-01                 1                  0.13
26   2017-01-01  2018-04-01                 1                  0.13
27   2017-01-01  2018-05-01                 2                  0.26
28   2017-01-01  2018-06-01                 3                  0.39
29   2017-01-01  2018-08-01                 1                  0.13
30   2017-02-01  2017-02-01              1752                100.00
31   2017-02-01  2017-03-01                 4                  0.23
32   2017-02-01  2017-04-01                 5                  0.29
33   2017-02-01  2017-05-01                 2                  0.11
34   2017-02-01  2017-06-01                 7                  0.40
35   2017-02-01  2017-07-01                 2                  0.11
36   2017-02-01  2017-08-01                 4                  0.23
37   2017-02-01  2017-09-01                 3                  0.17
38   2017-02-01  2017-10-01                 3                  0.17
39   2017-02-01  2017-11-01                 4                  0.23
40   2017-02-01  2017-12-01                 2                  0.11
41   2017-02-01  2018-01-01                 5                  0.29
42   2017-02-01  2018-02-01                 3                  0.17
43   2017-02-01  2018-03-01                 3                  0.17
44   2017-02-01  2018-04-01                 2                  0.11
45   2017-02-01  2018-05-01                 1                  0.06
46   2017-02-01  2018-06-01                 1                  0.06
47   2017-02-01  2018-07-01                 4                  0.23
48   2017-03-01  2017-03-01              2636                100.00
49   2017-03-01  2017-04-01                13                  0.49

In [ ]:
#The cohort analysis shows that customer retention is very low after the initial purchase. For example, the January 2017 cohort had 764 customers initially, 
#but only 3 customers (0.39%) returned in February and 4 (0.52%) returned in July. 
#This indicates that most customers made a single purchase and did not return in subsequent months.